parameters:
- name: environment  

stages:
- stage: TerraformInitAndPlan
  displayName: Terraform Init and Plan
  jobs:
  - job: TerraformInitAndPlan
    displayName: Terraform Init and Plan
    steps: 
    - task: CmdLine@2
      condition: Always()
      displayName: TfLint
      inputs:
        script: 'tflint --chdir=. --format=junit > $(System.DefaultWorkingDirectory)/tflint_report.xml'
        workingDirectory: '$(System.DefaultWorkingDirectory)/modules/LinuxVirtualMachine'

    - task: CmdLine@2
      condition: Always()
      displayName: Checkov
      inputs:
        script: 'checkov -d . -o junitxml --output-file-path $(System.DefaultWorkingDirectory)/'
        workingDirectory: '$(System.DefaultWorkingDirectory)/modules/LinuxVirtualMachine'
    
    - task: PublishTestResults@2
      condition: Always()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '*.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'

    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(WORK_DIR)'
        commandOptions: '-upgrade'
        backendServiceArm: 'azure-c'
        backendAzureRmResourceGroupName: 'dev-todo-rg-westus'
        backendAzureRmStorageAccountName: 'azuresaproter'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'
      
    - task: TerraformTaskV4@4
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(WORK_DIR)'
        commandOptions: '--var-file=${{ parameters.environment }}.terraform.tfvars'
        environmentServiceNameAzureRM: 'azure-c'

- stage: ValidationAndTerraformApply
  displayName: Validation and Terraform Apply
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  jobs:
  - job: ManualValidation
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: abc@abc.com 
        timeoutInMinutes: 1
  - job: TerraformApply
    dependsOn: ManualValidation
    steps:
    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(WORK_DIR)'
        commandOptions: '-upgrade'
        backendServiceArm: 'azure-c'
        backendAzureRmResourceGroupName: 'dev-todo-rg-westus'
        backendAzureRmStorageAccountName: 'azuresaproter'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(WORK_DIR)'
        commandOptions: '--var-file=${{ parameters.environment }}.terraform.tfvars'
        environmentServiceNameAzureRM: 'azure-c'            