pool: zelectric_pool

trigger: none

steps:
- task: TerraformInstaller@1
  displayName: Terraform Tool Installer
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
    commandOptions: '-upgrade'
    backendServiceArm: 'azure-connection'
    backendAzureRmResourceGroupName: 'testrg'
    backendAzureRmStorageAccountName: 'devopsstg543'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
    environmentServiceNameAzureRM: 'azure-connection'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
    environmentServiceNameAzureRM: 'azure-connection'